import React from 'react'
import '../WHblogs/WHblog.css'
import { Container, Col, Row } from 'react-bootstrap'
import WHnav from '../WHnav'
export default function WHintroBW() {
    return (
        <div>
            <WHnav />
            <Container>
                <Row>
                    <Col>
                        <div className="whblog">
                        <div className="sisters">
                                <h1>Bellz of War</h1>
                                <h2>Warhammer 40k: The Adepta Sororitas</h2>
                                <p><em>An introduction into the Sisters of Battle.</em></p>
                                <div className="byline">By Tyler Leavitt November 27th, 2021</div>
                                <p>Hello again everyone! Last week, we delved into the Astra Militarum, or Imperial Guard. For this week, I’ll be talking about the battle nuns and pyromaniacs of the Imperium: the Sisters of Battle, or Adepta Sororitas. Like before, I’ll talk about some brief background information, generic gameplay ideas, and finally give some basic starting lists. Without any further ado, let’s burn the heretics with our favorite nuns!</p>
                                <p><b>Adepta Sororitas - The Purifying Flame</b></p>
                                <img src="purflame.jpg" alt=""></img>
                                <p><em>A few Sisters of Battle venture into the unknown. Artist is MektaSatakOz on imgur.</em></p>
                                <p>The origins of the Adepta Sororitas takes us a few millenia after the Horus Heresy, during a time known in the Imperium’s history as the “Age of Apostasy.” During this time, it saw the near culmination of church and state within the Imperium, under a man named Goge Vandire. He had recruited a number of fanatical women as his own personal entourage called the Daughters of the Emperor, though they would turn on him after they learned about his deception to them. It’s a lot of lore I’m breezing past and if you’re interested in it, I highly recommend looking into it.</p>
                                <p>After the death of Goge Vandire, the High Lords of Terra decreed that the Ecclesiarchy, the church body of the Imperium, would no longer have any man serving in a military force for them. And to this extent, the Ecclesiarchy took advantage of the loophole in this decree. No MAN shall serve in a military force, but women are fair game. The Ecclesiarchy proceeded to build up the Sororitas as their own private military force, in the same manner as the Daughters of the Emperor. Each member was a religious fanatic, gladly giving their lives in the name of the Emperor to burn the heretic, mutant, and xeno.</p>
                                <p>In the present day, there are several orders that make up the Sororitas’s ranks. Each of the orders are maintained by various Canonesses, and these orders are essentially different armies. These are the equivalent of Space Marine Chapters or Imperial Guard Regiments in terms of gameplay and painting schemes. The Sisters of Battle on the battlefield are renown for their faith and zeal in combat, resulting in various miracles coming to life in the battle. This may result in a hail of bullets miraculously missing the Sister, to living Saints descending upon the battlefield to deliver their wrath.</p>
                                <img src="sisquad.jpg" alt=""></img>
                                <p><em>A squad of Sisters looking for more heretics to slay. Artist is MektaSatakOz on imgur.</em></p>
                                <p>A lot of people enjoy the Sisters, mostly because they’re badass women in terms of lore. They’re known for being extremely resilient despite the odds they face; while many Guardsman may run at the first chance their squad takes major damage, the Sisters will often fight to the death. There’s a story about a group of Sisters who are reportedly resurrected after each battle, proving that their faith in the Emperor is true. However, this is a lie; instead, the new members they recruit are indoctrinated into believing they are these fallen Sisters, to help keep up the guise of the Emperor’s powers. However, with a bit of the background lore and storytelling out of the way, let’s get into the gameplay.</p>
                                <img src="siscard.png" alt=""></img>
                                <p>Before I discuss any of their unique gameplay mechanics, and trust me, they’re VERY unique, let’s talk about their basic troop statline. The Sisters only have one troop choice: a Battle Sister Squad. This squad comes in at 4 Sisters with a Sister Superior, their equivalent of a sergeant, all for 55 points. This makes them a bit cheaper than a standard Space Marine Tactical Squad to field. In terms of stats, they’re a mix between the Space Marines and Guardsmen. Average move of 6”, average weapon skill, above average ballistic skill, below average strength and toughness, good save at a 3+. This results in a bit of a glass cannon style unit; they can hit often, and their boltguns will hit on par with the Space Marine bolters. If they get hit, it will almost always result in a wound on them, though their high save helps them in this regard. However, an added benefit of the Battle Sister Squad is that you can go up to 20 models in a single squad, in addition to 2 heavy weapons and 2 special weapons! This results in an absolute ton of firepower. This is a big theme with many Sisters’ units; lots of damage output, but low survivability. This brings me into the next part, talking about their unique abilities.</p>
                                <p>As the Adepta Sororitas, you get three unique abilities. Let’s start with discussing miracle dice, as this drives your other two abilities. Miracle dice are a separate dice pool that you roll at the beginning of the game, and add new ones for various actions. You can use these miracle dice at any time as essentially a reroll to the miracle dice’s rolled number. For example: let’s say I roll 2 miracle dice, and get a 4 and a 6 round 1. In round 3, one of my important units is about to die, and I failed their armor save. I can switch out the armor save’s roll with that 4 or 6 depending on what I needed, thereby saving the unit. This is obviously a very powerful tool, and you as a Sororitas player should learn when the best time to use them would be.</p>
                                <p>As for the other two abilities, there are Sacred Rites and Shield of Faith. Sacred Rites grants your army a wide buff depending on the rite you choose at the beginning of the game, or you can receive two randomly. These buffs can be simple, from +1 to advance and charge rolls, to more advanced, such as a bonus to Deny the Witch tests. This leads me to the Shield of Faith, which has two effects. First, all units with this have a 6+ invulnerable save. This may seem little in comparison, but hey, it’s at least something. Secondly, units with this ability may deny one psychic power as if it were a psyker. In return for essentially every unit being able to deny, you only roll 1d6 instead of the standard 2d6. If the result was a 6 or higher than the result of the psychic test, you deny their psychic power. This is a bit niche, but can be very good. It requires your opponent to bring some psyker units, but in return you have a chance of completely disregarding many of their battle plans that revolve around psychic abilities.</p>
                                <p>Now, with the abilities out of the way, let’s talk about general gameplay you can expect from the Sororitas. As previously mentioned, they’re a bit like glass cannons. They can get some good firepower on the field, but if they get hurt, they’re gonna get hurt. Make use of your miracle dice and various abilities your units all have. You will be amazed at how far your troops will be able to get with clever use of miracle dice and Sacred Rites.</p>
                                <img src="sisminis.jpg" alt=""></img>
                                <p><em>A well painted group of sisters. Artist is ms07b3 on dakkadakka.</em></p>
                                <p>Lastly, as always, here’s a sample 1000pt beginner list I think is fun to play. I only have one to give this time around; the Sisters are a relatively “new” faction, at least in 9th edition. As such, there’s not as many models or ways to play as with the Space Marines or Guard. Regardless, let’s take a dive into this list</p>
                                <p>Adepta Sororitas Army (995pts):</p>
                                <p>Order Convictions: Ebon Chalice</p>
                                <p>Honestly, there’s a few routes you could go here. I went with Ebon Chalice, as I thought being able to always choose two Sacred Rites would allow yourself plenty of flexibility regardless of the enemy you face. Additionally, discarding a miracle dice for a guaranteed 6 is always nice. You could also chance to Sacred Rose to get a 50/50 shot of getting back miracle dice when you use it, or Valorous Heart to receive a 5+ feel no pain. Ultimately the choice is up to you, these are just the three I think are the most friendly to new players.</p>
                                <p>HQ: Canoness, 50pts; Bolt pistol, Chainsword, Indomitable Belief (Aura) warlord trait. The Canoness here is rather basic in terms of wargear. That’s because I chose to use the Canoness more in a buffing role. She naturally receives the Lead the Righteous aura ability, which allows core units within 6” to reroll hit rolls of 1, which should bump up the number of landed attacks on enemies. Additionally, you have the Indomitable Belief warlord trait, which buffs the Shield of Faith invulnerable save by 1, meaning units close to the Canoness are saving on a 5+. This will help increase the survivability of your Sisters squads. Alternatively, you can go with the Beacon of Faith ability for some miracle dice generation.</p>
                                <p>Troops: 2 Battle Sister Squads, 110pts; 9 Battle Sisters, 1 Sister Superior. Once again, rather basic on the troops choice. I chose to go for two squads rather than one big squad to help secure objectives. Read back above on what the Sisters squad can do in combat. Keep them alive, and they’ll dish out some good damage.</p>
                                <p>Elites: Celestian Squad, 130pts; 9 Celestians, 1 Celestian Superior. Sisters Repentia, 140pts; 10 Sisters Repentia</p>
                                <p>The Celestian squad is an upgraded Battle Sister squad. These ladies will act as the Canoness’s main guards, thanks to their Bodyguard and Sworn Protectors abilities. You could probably drop them for another squad of Sisters, and adding on one or two additional sisters in those squads. The Sisters Repentia are an expendable melee unit that offers as a way to gain back at least one miracle dice. However, they’re a bit tankier than they might seem, and they’ll also deal a lot of damage if they get close enough.</p>
                                <p>Heavy Support: Castigator, 170pts; Battle Cannon, Hunter-killer Missile. Retributor Squad, 150pts; 2 Armourium Cherubs, 1 Retributor Superior, 4 Retributors with Multi-Meltas</p>
                                <p>Here’s where we get into the real major damage dealing tools you have at your disposal. The Castigator is your mainline battle tank, equivalent to a Space Marine Predator. However, the Battle Cannon has the option of firing either a Pyro or Sanctified shell, each extremely deadly to infantry and heavy targets. The Retributors are your heavy weapons team, which I have equipped them all with Multi-Meltas. The Meltas deal a good amount of damage, especially if you can get them close. Additionally the Armourium Cherubs I attached on the squads allow the Retributors to fire their weapons twice in a turn, up to two times. This should easily level the playing field against anything major in your way.</p>
                                <p>Dedicated Transport: Immolator, 135pts; Hunter-killer Missile, Immolation Flamers. Lastly, we arrive at the transport choice. The Immolator is a large flamethrower tank that doubles as a transport. Load it up with your Retributors, and keep the enemies at bay with the Immolation Flamers.</p>
                                <img src="canoness.jpg" alt=""></img>
                                <p><em>A Sister Canoness looks out onto the battlefield, as reinforcements are dropped from above. Artist is MektaSatakOz on imgur.</em></p>
                                <p>I think that'll cover it for this week on the Sororitas. They’re a fun faction, with some very unique and fitting mechanics. Next week, I’ll discuss the toaster-loving Adeptus Mechanicus! May the dice gods favor you!</p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                </div> 
                        <div className="guard">
                                
                                <h2>Warhammer 40k: The Astra Militarum</h2>
                                <p><em>An introduction into the Imperial Guard.</em></p>
                                <div className="byline">By Tyler Leavitt November 7th, 2021</div>
                                <p>Welcome back to my introductions into Warhammer 40k. Last week, I covered the Adeptus Astartes, the angels of death of the Imperium. This week, I’ll be talking about the Hammer of the Emperor: the Astra Militarum. Like last week, I’ll cover some brief background information, then get into some generic gameplay ideas about the faction, and end off with some starter lists. For now though, let’s talk about life in the Guard.</p>
                                <p><b>Astra Militarum - The Hammer of the Emperor</b></p>
                                <img src="hammeroe.jpg" alt=""></img>
                                <p><em>Brave soldiers of an unknown regiment holding the line. Artist is also unknown.</em></p>
                                <p>Now, to begin my talks about the Militarum, I want to open up with two quotes from General Sturn of the 412th Cadian Regiment:</p>
                                <p>“Although the Golden Throne of Terra orbits a distant star far from here, the Emperor’s hand is on your shoulders today. You have fought and displayed bravery and loyalty far above your calling as guardsmen. You have faced the full brunt of an Ork WAAAAGH!, as well as stared down the horrors of the warp in the fallen space marines. And in that, I am honored to have led you!”</p>
                                <p>“To each of us falls a task, and all the Emperor requires of us Guardsmen is that we stand the line, and we die fighting. It is what we do best: we die standing.”</p>
                                <p>These quotes perfectly encapsulate what it means to be part of the Imperial Guard. They’re men and women who either volunteer, or in some cases drafted, to fight for the Imperium. They face insurmountable odds on the battlefield and must fight tooth and nail against daemons, xenos, and heretics alike. The space marines may know no fear, but the guardsmen must hold the line no matter the costs.</p>
                                <p>The Astra Militarum can be seen as early as the Great Crusade. During this time, the space marine legions would have gone from world to world conquering them and bringing them all back into the Imperium. The Militarum would have acted as auxiliary units to the space marines; they were not the main fighting force. They would’ve acted as rear guard units, or stayed behind as a planetary defence force. It’s only after the introduction of the Codex Astartes and the dissolution of the legions that the Militarum began to take a larger military role in the Imperium. In current M42, most guard regiments still act as defence forces, but they can no longer rely on a space marine legion or chapter to aid them in battle. They have to defend these planets to the bitter end.</p>
                                <p>I think that’s what draws most people to the Guard; they’re normal people who are serving in the military, but face down horrors we can’t even think of. They’re all very badass, and a very good reason why they’re one of my favorites.</p>
                                <img src="krieg.jpg" alt=""></img>
                                <p><em>Brave soldiers of an unknown regiment holding the line. Artist is also unknown.</em></p>
                                <p>The Death Korps of Krieg taking a new position. Artist is unknown.</p>
                                <p>I also can’t talk about the Militarum without discussing the various regiments. While the Militarum takes men and women across the Imperium, there are several worlds that have proven to make for extremely good soldiers. The Cadians are the most famous of these worlds; Cadia is a fortress world that acted as a gate for Chaos. The forces of Chaos would have to attack Cadia to push into the Imperium at large, but Cadia managed to persevere almost every time. It was only at the end of the 41st millennium that Cadia finally fell, but the Cadians proved to be so tough and resilient that the planet had to be destroyed by Chaos.</p>
                                <p>Additionally, there are the Death Korps of Krieg, who are exactly what you think about for World War I German soldiers. They hail from the world of Krieg, a planet that was so ravaged by a civil war that the surface is no longer hospitable. When the loyalist Krieg forces won and were brought back into the Imperium, they had nothing to give as a tax to the Imperium. Instead, they donated their finest regiments, and to this day they continue to donate the best siege warfare experts the Militarum has to offer. They are so strapped with guilt that their planet could have potentially fallen to Chaos, that they have become fanatical to an extreme degree. Typically, Commissars are meant to keep the soldiers in line and make sure they don’t break; Krieg Commissars have to make sure that the Krieg soldiers don’t rouse themselves into a frenzy and get killed before orders are given.</p>
                                <p>There are many others, each fulfilling a different fantasy. While Krieg might be World War I Germans, there’s the Vostroyans who are Russians, or the Tallarn who are Arabic. The regiments of the Imperial Guard are as unique as they are numerous. However, now let’s talk about how they play.</p>
                                <img src ="yellowguard.jpg" alt=""></img>
                                <p><em>A well painted guard army. Once again, I don’t know who did this art.</em></p>
                                <p>The Astra Militarum is best summarized by having lots of expendable infantry, backed by tough and numerous vehicles. They’re primarily a horde faction, you field an absolute crazy amount of guardsmen for very little. However, that doesn’t mean you should underestimate them; the Leman Russ main battle tank is incredibly tough, durable, cheap, and effective. The Militarum also has plenty of artillery weapons, including one of the best in the game: the Manticore. First, let’s look at the stats of a basic guardsman squad:</p>
                                <img src="guardsheet.png" alt=""></img>
                                <p>As I said before, we’ll be making plenty of comparisons with the basic space marine tactical squad. Here, you can see that guardsmen have worse weapons and ballistics skills, lower strength and toughness, words leadership, and a worse armor save. On top of that, their lasguns are extremely weak as well, with only a strength 3 with no AP. However, for almost half the cost of the tactical squad, you’re getting 9 guardsmen and 1 sergeant. Additionally, you can trade out a guardsman for one with a special weapon, one with a vox-caster, or a heavy weapon team. Personally I wouldn’t worry much  about most of these options outside of the vox-caster.</p>
                                <p>What does the vox-caster do, you might ask? Well, as the Astra Militarum, you have a special faction ability your officers (mostly HQ) units can do: orders. You have several different orders that an officer can issue to various squads, and this range is increased if that officer and your squads have vox-casters. These orders are really where the power of a guardsmen starts to shine. First Rank, Fire! Second Rank, Fire! can double the amount of shots you’re getting out of a single squad, which can easily come up to nearly 40 shots out of a single guardsman squad. Move! Move! Move! can offer you a useful objective securing tool, and much more. If you want to play the Militarum, I suggest you learn these orders by memory. They’re critical to succeeding as the Militarum.</p>
                                <p>Let’s also talk about the artillery of the Militarum, because there are a ton. There’s the Basilisk and Earthshaker Carriage Battery, which are your classic artillery. The Basilisk just puts the artillery gun onto a mechanized chassis to make it more mobile and tougher. The Earthshaker cannon is a very fun weapon to use, even if it might not be the most competitively viable. If you want something even heavier, there’s the Deathstrike, which is a nuclear missile on wheels. It is incredibly not viable in competitive, as the missile takes far too long to fire, and the thing itself is expensive when compared to other artillery options, but it’s still a fun option to take. Lastly, that brings us to the Manticore. The Manticore is a mobile missile platform; it has 4 missiles that it can fire during the entire game, and these missiles will absolutely hurt anything and everything it hits. This is the best competitive use of an artillery unit the Militarum has.</p>
                                <p>Lastly, before we get into lists, I want to talk about the Leman Russ tank. This is your mainline tank as the Militarum, and it can be outfitted with any type of main cannon for whatever mission you want. The main production Leman Russ comes equipped with a standard battle cannon, or there’s the Executioner variant that comes with a mighty plasma cannon. My personal favorite is the Punisher variant; it replaces the main gun with a fearsome gatling cannon that shoots out 20 dice! Combine that with a tank Ace with the Weapon Expert trait for a fearsome strength 5, -1AP 20D6 weapon. It might not be competitive, but it sure is fun!</p>
                                <p>You have plenty more unit and tank options, but I’ll let you explore those on your own. For now, let me give some beginner lists.</p>
                                <p>Infantry Heavy Militarum Army (994 points):</p>
                                <p>This is going to be more of a “thematic” list than anything else. You’ll primarily be focused on infantry and artillery, with a few armored support vehicles.</p>
                                <p>Regimental Doctrine: Cadian</p>
                                <p>The Cadians work best here, as if you’re playing infantry focused you’re going to have some heavy guns. Combine this with Take Aim! to give a squad very high killing potential. Alternatively, you could also use Vostroyan or Armageddon. All 3 are viable options</p>
                                <p>HQ: Company Commander, 37pts; Boltgun, Cadia Superior Tactical Training Warlord Trai</p>
                                <p>This is going to be your basic HQ unit choice for the Militarum. Don’t expect him to do much combat, because that’s not his job. He’s supposed to stick close to a vox-caster and issue out orders like crazy, and that’s where his warlord trait comes into play. Superior Tactical Training lets him issue out potentially two orders to two different units, which can be devastating when used well.</p>
                                <p>Troops: 4 Infantry Squads, 60pts; 8 guardsmen, 1 sergeant, 1 vox-caster. Here we have your main line infantry. Like I said earlier, don’t expect them to do much killing on their own. They’ll be able to get in a few kills here and there, but don’t count on it. Use them primarily for securing objectives and holding the fort.</p>
                                <p>Elites: 1 Command Squad, 45pts; 1 veteran, 1 veteran w/ medi-pack, 1 w/ special weapon, 1 w/ vox-caster; 1 Commissar, 25pts; 2 Special Weapons Squads, 49pts; 3 guardsmen, 3 w/ plasma guns; 2 Special Weapons Squads, 49pts; 3 guardsmen, 3 w/ meltagun</p>
                                <p>Here is when we get into the real meat and potatoes of the list. Let me go through these one by one. First, the command squad are your commander’s bodyguards. Keep them near him. The medic can keep him healed, the special weapon can do a bit of damage, and the vox-caster is always important. Next, the Commissar. He’s not super important, but acts as a good leadership buff to your infantry. You could replace him for someone else, however, such as an extra special weapon on the command squad. The plasma special weapon squad is designed for more of an anti-infantry role. They should be able to take out most things that come their way, especially if you combine with Cadia’s special doctrinal trait. Lastly, the Meltaguns are some infantry anti-armor power. Get them close to a vehicle, and watch them do work.</p>
                                <p>Fast Attack: 1 Hellhound, 118pts; heavy flamer, hunter-killer missile, inferno cannon, storm bolter. The Hellhound is a fast mechanized unit equipped with a powerful flamethrower. Here, I’ve gone all in solidifying its role as a close-ranged fire support unit. The heavy flamer and inferno cannon will kill most infantry it attacks, and the storm bolter will provide a few shots here and there. The missile is to help with any vehicle you might have problems with.</p>
                                <p>Heavy Support: 1 Basilisk, 125pts; 1 Heavy Weapons Squad, 65 pts; 3 with Lascannons; 1 Heavy Weapons Squad, 50pts; 3 with Autocannons. Heavy support is exactly what you think you get. The Basilisk can provide some heavy fire support wherever you need it on the board. The lascannon heavy weapons squad is designed for an anti-vehicle role, while the autocannons are anti-infantry. Not much to say here, just keep them in one place and they’ll do fine.</p>
                                <p>Dedicated Transport: 1 Chimera, 93pts; 2 heavy flamers, 1 storm bolter, and hunter-killer missile. Lastly, we have the Chimera, and you’ll notice some similarities with the Hellhound. All things considered, it acts in a similar role to the Hellhound, but it can carry infantry. Combine with the meltagun special weapons squads, and you have a vehicle that can offer very quick death to enemies.</p>
                                <p>Armor Heavy Militarum Army (1000 points):</p>
                                <p>The opposite of the list beforehand, this focuses on primarily tanks and armored units with very little infantry support.</p>
                                <p>Regimental Doctrine: Cadia</p>
                                <p>Once again, we’re going with Cadia. This is more for the reroll hits of 1 than the Take Aim! bonus. However, you could also use Tallarn if you want to keep your units moving, which is always a good choice to go with.</p>
                                <p>HQ: Tank Commander, 250pts; 2 plasma cannons, augur array, hunter-killer missile, lascannon, Demolisher Siege Cannon, Steel Commander Tank Ace. Here’s your main HQ unit, but unlike in the past, this is focused on combat rather than support. That’s why I went with a Tank Ace trait over a Warlord one; the Steel Commander lets it still fulfill a support role, but in the end it’s still a full on combat unit. Everything about it I made geared for it to be a long ranged killing machine.</p>
                                <p>Troops: 3 Infantry Squads, 55pts; 9 guardsmen, 1 sergeant. Not much to say here, they’re just here to help take objectives.</p>
                                <p>Fast Attack: Armoured Sentinels, 40pts; 1 with multi-laser and hunter-killer missile; Hellhounds, 115pts; 1 with heavy flamer, inferno cannon, and hunter-killer missile. As with the infantry list before, the Hellhound is a close ranged killing machine. Keep it protected with your tanks. The Sentinel I mostly threw in to take up a few more points. It likely won’t do much, but can act as a quick scout/flanking option if you need it to be.</p>
                                <p>Heavy Support: Leman Russ Battle Tanks, 430pts; 2 Leman Russ Demolishers with 2 plasma cannons, augur array, hunter-killer missile, lascannon, and Demolisher siege cannon</p>
                                <p>Here we have some duplicates of your tank commander, and once again they will destroy anything you set them upon. Keep them close to your commander for tank orders, but this is your main focus in battle. Treat them well, and they’ll treat you well.</p>
                                <img src="bigguard.jpg" alt=""></img>
                                <p><em>A massive Militarum army column that found Chaos forces. Artist is unknown, but I believe this is from Gamesworkshop.</em></p>
                                <p>I think that’ll about do it for this week’s faction introduction. Like I said before, the Militarum are one of my personal favorite factions. It was a blast to write up this post! Next week, continuing on with the servants of the Emperor, we’ll be talking about the Sisters of Battle, or Adeptus Sororitas. May the dice gods favor you!</p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                <p></p>
                                </div>
                        <div className="astartes">
                                
                                <h2>Warhammer 40k: The Adeptus Astartes</h2>
                                <p><em>An introduction into space marines.</em></p>
                                <div className="byline">By Tyler Leavitt November 1st, 2021</div>
                                <p>I’m back to continue my introduction into Warhammer 40k! Last week, I gave a general introduction into the universe and how best to get started in the hobby. The next month or two I’ll be talking about the various factions in depth. I will cover each faction’s lore and background, how they play, and give some tips for starting armies or how to develop an army. Please know that while I am experienced, I don’t know each faction in depth. I don’t know the best strategies with everyone, but I know general strategies and builds that seem good to me. With that out of the way, let’s begin with the angels of death: the Space Marines!</p>
                                <p><b>Adeptus Astartes - The Angels of Death</b></p>
                                <img src="imperialfist.jpg" alt=""></img>
                                <p><em>An Imperial Fist marine holds the line. Artist credit: Anonymous, found on WallpaperFlare.</em></p>
                                <p>To start off with, let’s talk about the poster boys for 40k: the Adeptus Astartes, or Space Marines. The space marines were created when the Emperor of Mankind first went out to reclaim all human worlds back into his new Imperium. He created 20 children that would become known as the Primarchs. From these Primarchs, he then created 20 legions of space marines, each the genetic children of the Primarchs. The space marines would serve as the main fighting force of the Imperium until the end of the Horus Heresy, which saw the Imperium split by a massive civil war. Primarchs and space marines fought each other in bloody battle, and in the end the Emperor sacrificed himself to defeat his fallen children.</p>
                                <p>After the Horus Heresy, one of the loyalist Primarchs named Roboute Guilliman created the “Codex Astartes,” rules that would dictate the formation and strategies of the space marines. No longer would they be organized into massive legions; instead, they would be formed into 1000 man “Chapters,” made of 10 companies with 10 squads each. In the year M42, most loyalist Chapters still follow these rules laid out in the Codex. However, there are a few that deviate from it, but are still loyal servants of the Emperor.</p>
                                <p>Being the poster boys for what represents Warhammer 40k, the space marines get the most love of any faction in the entire game. For those who read my last 40k article, you’ll remember that I recommend the space marines as the best faction to get into the game, and I still stand by that statement. The truth is, the space marines have some of the most well rounded troops out of any faction. They don’t excel at any area in particular, making them a jack of all trades faction. This allows a new player to expand their space marine roster into several different directions, or play as space marines until they learn what they enjoy doing, and then get into a faction that does it better. You’ll find that your stats are usually the ones that most people compare their own troops to as a baseline. Let’s take a look at the two main frontline troops you’ll have as a space marine player: the Intercessor Squad, and Tactical Squad.</p>
                                <img src="astartescard.png" alt=""></img>
                                <p>This will be your Tactical Squad. These consist of the original space marines before getting the “rework” into Primaris marines, which are just brand new space marines. A tactical squad can consist of a minimum of 4 space marines and a sergeant, up to 7 space marines, a heavy weapons marine, a special weapon marine, and the sergeant. The weapons specialists give your marines extra flexibility in combat with a variety of weapons, but I won’t cover those for now. Right now, pay attention to the stats. A space marine can move 6”, which is about average. They have a weapon and ballistic skill of 3+, which means that they’re hitting a bit more than half the time, as you’re hitting on 3 or above on a D6. Your strength and toughness are average for a troop choice at 4s. You get 2 wounds, which is above average for most troops and is remarkably tough. 1 attack (2 on the sergeant) which is normal. A 7 leadership is fairly average once again, and a 3+ armor save is pretty good. All of this combines into a fairly resilient and adaptable troop choice.</p>
                                <img src="intercessorcard.png" alt=""></img>
                                <p>Next, let me talk about the Primaris Intercessors. When looking at these compared to the tactical marines, you’ll notice two main things: one, these guys are more expensive. And two, they have the same statline as the tactical marines. And for both, you’d be correct. The area that the intercessors have a difference in are their weapons, the Bolt Rifle compared to the standard Bolter, or Boltgun. The Bolt Rifle has an extra 6” of range, and AP -1. This makes your baseline marine have much more ranged firepower than the tactical marine, but there’s more. You lose the ability to take specialist weapons marines from the squad; instead, you can take grenade launchers, or 3 different types of rifles. This means that while the squad has less flexibility than the tactical squad, they have more anti-infantry firepower than them too.</p>
                                <p>In the end however, these are the stats that most people will compare their own troops to. For all of my faction introductions, I’ll also be making comparisons to these space marines as well. Now, how about some lists? I’ll give a few starting lists at 1000 points. Most battles are fought at 2000 points, so this gives you some choices for how you want to grow the army as well.</p>
                                <p>Beginner Army Non-Primaris (990 points):</p>
                                <p>This list will have no Primaris marines in it, and instead focus on the original space marines.</p>
                                <p>Ultramarines Chapter: No reason in particular for this choice, other than it being a good baseline chapter to start with. You can easily switch this out for any other chapter.</p>
                                <p>HQ: Captain, 95pts; Iron Resolve warlord trait, Master Crafted Boltgun, Relic Blade. The captain is your baseline HQ unit without getting into anything else. He’s generic, but he’ll do just fine for a starting army. He has the master crafted boltgun and a relic blade, giving him both ranged and melee staying power. The Iron Resolve warlord trait also makes him tougher to kill, which is a good starting trait while you’re learning the game.</p>
                                <p>Troops: Tactical Squad, 200pts; 7 space marines, 1 sergeant, marine with heavy bolter, marine with plasma gun. Tactical Squad, 205pts; 7 space marines, 1 sergeant, marine with lascannon, marine with meltagun.</p>
                                <p>Here I’ve given you two squads of tactical marines, both geared towards different roles. The first squad has a heavy bolter and plasma gun, giving it more anti-infantry firepower. The second squad has a lascannon and meltagun, giving it more anti-armor firepower.</p>
                                <p>Elites: Dreadnought, 120pts; Assault cannon, Dreadnought combat weapon w/ Storm BolterThe Dreadnought is one of the most iconic units of the space marines. A large war walker with a giant fist and a massive support cannon. Yes please! This loadout makes the dreadnought a jack of all trades unit; assault cannon and storm bolter give some massive ranged firepower, while the combat weapon gives it a mean melee weapon.</p>
                                <p>Fast Attack: Assault Squad, 130pts; 3 space marines, sergeant with combat shield and thunder hammer, marine w/ Eviscerator, jump packs.Here we have your main melee squad. The jump packs give the squad 6” extra movement, which means they can quickly get into combat. The eviscerator and thunder hammer give a massive boost in melee, while the combat shield gives the sergeant a bit of durability with an invulnerability save.</p>
                                <p>Heavy Support: Devastator Squad, 150pts; 1 sergeant, 1 marine with heavy bolter, 1 marine with plasma cannon, 1 marine with lascannon, 1 marine with multi-melta. This is your main ranged squad. I have it built to be extremely flexible with the weapon choices; the heavy bolter is for anti-infantry, plasma cannon for a heavy AOE infantry or armor tool, lascannon for armor, and multi-melta for close-ranged firepower.</p>
                                <p>Dedicated Transport: Rhino, 90pts; 2x Storm bolters, Hunter-killer missile Lastly is a Rhino. This Rhino has a bit of firepower, but that’s not the main reason why it’s here. The reason is because it can carry 10 marines, which gives you some extra maneuverability. Combine this with devastators, and you’ll find that you can drop your devastators right into the middle of battle where they’re needed. The rhino can also act as a good defensive tool too, so use it to your advantage!</p>
                                <p>Beginner Primaris Army (997pts):</p>
                                <p>This army will focus solely on Primaris marines.</p>
                                <p>Ultramarines Chapter: Same reason as above. No real good reason, it’s just a good beginning chapter to get introduced with.</p>
                                <p>HQ: Primaris Captain, 90pts; Iron Resolve warlord trait, Master-crafted auto bolt rifle. A similar loadout to the captain as above, but you’ll notice the lack of a melee weapon. Primaris are going to be stronger shooting wise than the normal space marines, which will be a theme throughout the list.</p>
                                <p>Troops: Heavy Intercessor Squad, 140pts, 4 intercessors, 1 sergeant; x2 Intercessor Squad, 180pts; 8 intercessors, 1 sergeant. You’re losing more bodies per squad here compared to the normal marines. However, you make up for it in how much more powerful your weapons are. You can easily drop the heavy intercessors for more normal intercessors, or a third squad of them. I added them in as they’re a longer ranged anti-infantry option if you wanted to use them. I have them equipped with the Executor bolt rifle as AP is pretty good, especially in an anti-infantry role, but as I said you might want to drop these for more Intercessors.</p>
                                <p>Elites: Aggressor Squad, 270pts; 2 Aggressors, 1 Sergeant w/ Boltstorm Gauntlets and Fragstorm Grenade Launcher; Reiver Squad, 180pts; 8 Reivers, Reiver Sergeant w/ combat knife</p>
                                <p>Something you’ll notice is that the melee firepower (Reivers) and what I’m deeming the ranged firepower (Aggressors) are counted as elites rather than heavy support and fast attack like above. I’m not sure the exact reason for it, other than the Primaris get all the love. Anyways, the Aggressors at the very least fulfill a different role from the Devastators. They don’t have long range; instead, they have heavier AOE boltstorm gauntlets with blast to really tear into hordes of enemies. Reivers are still similar to the assault squad, but they don’t have jump packs which impacts their speed. In turn, they get the Terror Troops aura, which lowers leadership for enemies close to them.</p>
                                <p>Dedicated Transport: Impulsor, 110pts; 2x storm bolters. Lastly is the Impulsor, which will fulfill a role similar to the Rhino. It carries less troops than the Rhino, 6 compared to 10, but in turn it’s slightly faster, and a bit tougher. It also has the Assault Vehicle ability, which gives even more bang for your buck than the Rhino. Combine with Heavy Intercessors for a fast and mobile hit squad.</p>
                                <img src="ultramarines.jpg" alt=""></img>
                                <p><em>The Primaris of the Ultramarines march to war!</em></p>
                                <p>With these lists, you can branch out depending on what you enjoyed doing in a few games. Do you enjoy melee? Then perhaps going into Space Wolves or Black Templars, and then getting more melee focused troops. Like ranged? Maybe Imperial Fists or Salamanders then. Want more toughness? Iron Hands. As for units, there’s an absolute ton of them, so you have a lot of ways to expand your burgeoning space marine army!</p>
                                <p>That will be all from me for today. Next week, I plan on continuing on with the Imperium of Man by looking at one of my favorite factions, the Astra Militarum, or Imperial Guard. May the dice gods favor you!</p>
                                <p></p>
                            </div>
                            <div className="whintro">
                                <h2>What Is… Warhammer 40k?</h2>
                                <p><em>An introduction into the 40k universe, including story and tips to start playing.</em></p>
                                <div className="byline">By Tyler Leavitt October 25th, 2021</div>
                                <p>Hello everyone! My name is Tyler, and I’m here to act as your guide into the wonderful world of… wait, no, wrong game. I’m here to guide you through the depressing yet still badass universe of Warhammer 40,000. Whether you’re completely new to the game, or a veteran, my goal is to help you learn something about it.</p>
                                <p>So… why get into Warhammer 40,000? Maybe you have some friends who play it and you wanted to join in. Maybe you saw the pretty miniatures in your local game store. Maybe you just like the aesthetic. Everyone joins the game for their own reasons, and they have their own ways of enjoying the universe. Personally, I love learning about the lore, which often impacts how I want to play the game itself. I’m not concerned about what the most overpowered faction is, I just want to enjoy the factions I like from the lore. Of course, you CAN be competitive as well, but that’s not my realm of expertise. Instead, I’ll give a brief rundown on the universe and the game itself, alongside giving some starter tips to help you if you have nothing to start with!</p>
                                <p><ins>The Universe</ins></p>
                                <p>As I mentioned before, I love learning and talking about the lore. There’s so much to talk about though that it can be a bit overwhelming to start! The general summary I always give to new people is this:</p>
                                <p>The universe is in the 42nd millennium. Humanity has spread across the stars, forming a great empire known as the Imperium of Man. However, they are always at war, either with aliens (called xenos) or locked in a long civil war amongst themselves with the forces of Chaos. The brave men and women of the Imperium have to face down terrible odds, against the massive green hordes of the Orks, the technological supremacy and fearsome battlesuits of the Tau, or the ever consuming hunger of the Tyranids… </p>
                                <img src="nids.jpg" alt=""></img>
                                <p>Brave soldiers of the Imperial Guard, facing down a Tyranid invasion. Artist credit: lathander1987 on Deviantart.</p>
                                <p>And yet, the Imperium of Man holds against these threats. The Imperial Guard, the main military fighting force of the Imperium, holds the line against these foes with a seemingly endless supply of manpower, and the thunder of their mighty guns and tanks.</p>
                                <p>However, the one thing that everyone knows from Warhammer 40k are the mighty space marines. Tall, strong, and heavily armored, the space marines fight wherever they are needed. A squad of space marines can easily turn the tide of battle for the Imperium.</p>
                                <p>Besides the space marines, the other main fighting force of the Imperium are the Sisters of Battle. They are religious fanatics, fighting to the death for the God Emperor of Mankind. They can best be described as battle nuns. Prayers and hymns protect them in battle, while they march forward and burn the heretics and xenos. </p>
                                <img src="orksm.jpg" alt=""></img>
                                <p><em>Ultramarines fighting in close quarters combat against the Orks. Artist credit: ukitakumuki on Deviantart.</em></p>
                                <p>There’s a ton of other things I haven’t touched on, but there are plenty of ways to learn about the universe if you’re interested. Personally, one of my favorite things to do is to use the Warhammer 40k wikipedia to go delving into a topic. I’ll pick something that interests me, and start reading the article. If I find something else I want to read or learn about, I’ll open up a new tab with it to read later. There are also a ton of videos on YouTube as well! My personal favorite is 40k Theories’ 40k Lore for Newcomers. He goes over a lot of lore topics in Warhammer 40k and explains them for you. He also has a pretty good timeline video of the entire 40k universe. Bricky has a few videos explaining each faction in 40k; he explains them in a comedic fashion, but they’re good explanations. Adeptus Ridiculous also has a ton of lore videos. Find something that suits you, and listen to them while in the car or working on something else!</p>
                                <a href="https://youtu.be/UszZz_XC1YE" target="_blank" rel="noreferrer" alt=""><em>Link to that entire 40k timeline I mentioned… there’s going to be a lot of confusion if you first go into it!</em></a> 
                                <p><ins>The Game</ins></p>
                                <p>Now… onto the game itself. Let me preface this by saying that the hobby is expensive, especially for some factions. There are easy ways of getting past this however, and other ways to enjoy Warhammer in terms of video games. Let me start by talking about the tabletop wargame, however. </p>
                                <p>When you first look at starting an army, you’re going to notice the awesome paint jobs that people have done online or on the box. They do not come like this; they don’t even come built. You will have to build your figures yourself, and paint them yourself (or get a friend to do it). Before you turn away or think to yourself that there’s no way you can paint them, that’s what the internet is for! There are plenty of guides to help you, and don’t give up if your first models don’t turn out well! The main thing with building and painting is learning. Keep practicing and keep learning, and you’ll find yourself improving with each model you paint!</p>
                                <img src="plastic.jpg" alt=""></img>
                                <p><em>Some unpainted Primaris Marines, standing with some Warhammer Fantasy models.</em></p>
                                <p>As for the game itself, there’s plenty of armies, and for some armies in particular, there can be a ton of models to look through. The next question you should ask yourself about starting an army is: what is my budget? What am I looking for in an army? I plan on doing more in depth looks into each of the factions, but if you know nothing about the universe and don’t want to spend much on the game, there’s a way to enjoy the game without busting the bank. </p>
                                <p>And that would be Kill Team, or Kill Team Classic rather. Warhammer 40k focuses on large armies duking it out on the battlefield, and with how many squads you need or heavy firepower, the costs can tally up quickly. With Kill Team, it focuses on an elite squad combat system. Each faction is narrowed down to a select few models, and there’s your entire list. For some factions, you can easily get away with purchasing a single box of models. Kill Team Classic still plays in a very similar fashion to standard 40k as well, meaning that you can learn the intricacies of the game without getting too invested into it. </p>
                                <p>And for those of you wondering why I say “Kill Team Classic,” well there’s a reason for that. The recent edition to Kill Team changed the game entirely, making it a completely new game rather than a small scale 40k. You can still use the models from the new edition though, and there are some beautiful models that come with the starter kit. But I would recommend finding a PDF of Kill Team Classic online and starting there.</p>
                                <img src="orkvsnazi.jpg" alt="orkvsnazi"></img>
                                <p>After getting your feet wet with Kill Team, or maybe you have some friends who are willing to tone down their own armies with you, you can choose what army you want to get into. If you’re more of a money-oriented kind of person, I would steer away from Horde style factions, such as the Imperial Guard, Orks, and Tyranids. The best armies to start off with here would be Harlequins and Custodes. They require very few models in their armies, and they’re pretty solid overall. However if these do not suit your fancy, I would recommend looking on EBay for models. Most of the time they will come painted, so you might have a batch of mixed models making up your entire army. If you’re worried about gameplay, the Space Marines are the most well rounded faction despite their overwhelming model roster. Get some basic squads of space marines, with some devastators and assault squads for a well rounded infantry list. If you want a vehicle, you can’t go wrong with a Rhino or a Predator. From there, you can expand out your list depending on how you enjoy playing; you can get Primaris Intercessors for a stronger frontline, Bladeguard Veterans for a melee focused infantry unit, or Primaris Aggressors for some heavy infantry fire support. There’s tons of ways to expand out your army from there!</p>
                                <p>If you know what kind of playstyle you enjoy, I have some recommendations as well. If you prefer ranged combat, the Astra Militarum (aka Imperial Guard) or Tau are the best choices for you. The Guard focuses on quantity over quality with some great artillery and tanks, while the Tau feature some heavy hitting firepower and mechs. If you like melee, Orks, Tyranids, and Drukhari and the way to go. The first two are more horde style, so if you want to save on money, the Dark Eldar (basically just Dark Elves) are the best choice for you. The Tyranids can be more focused and specialized than the Orks, but nobody can hate the Orks because of their fun mechanics and lore! Want a fast and maneuverable team? Craftworld Eldar or Harlequins. Want a tanky team? Necrons or Death Guard. Want a spellcasting team? Craftworld Eldar or Thousand Sons. There are plenty of playstyles to choose from!</p>
                                <p>With that, I think I’m finally done explaining Warhammer 40k to you. I didn’t cover the rules and gameplay, nor the factions themselves. The best way to learn the game is to play with friends and meet some new people! With that concluded, I wish you all luck in your games. May the dice gods favor you!</p>
                                <img src="ssm.jpg" alt=""></img>
                                <p><em>For the Emperor! Artist credit: pierreloyvet on Artlords.</em></p>
                                <p></p>
                                <p></p>
                            </div>
                        </div>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}