import React from 'react'
import '../WHblogs/WHblog.css'
import { Container, Col, Row } from 'react-bootstrap'
import WHnav from '../WHnav'
export default function WHintroBW() {
    return (
        <div>
            <WHnav />
            <Container>
                <Row>
                    <Col>
                        <div className="whblog">
                            <div className="whintro">
                                <h1>Bellz of War</h1>
                                <h2>What Is… Warhammer 40k?</h2>
                                <p><em>An introduction into the 40k universe, including story and tips to start playing.</em></p>
                                <div className="byline">By Tyler Leavitt October 25th, 2021</div>
                                <p>Hello everyone! My name is Tyler, and I’m here to act as your guide into the wonderful world of… wait, no, wrong game. I’m here to guide you through the depressing yet still badass universe of Warhammer 40,000. Whether you’re completely new to the game, or a veteran, my goal is to help you learn something about it.</p>
                                <p>So… why get into Warhammer 40,000? Maybe you have some friends who play it and you wanted to join in. Maybe you saw the pretty miniatures in your local game store. Maybe you just like the aesthetic. Everyone joins the game for their own reasons, and they have their own ways of enjoying the universe. Personally, I love learning about the lore, which often impacts how I want to play the game itself. I’m not concerned about what the most overpowered faction is, I just want to enjoy the factions I like from the lore. Of course, you CAN be competitive as well, but that’s not my realm of expertise. Instead, I’ll give a brief rundown on the universe and the game itself, alongside giving some starter tips to help you if you have nothing to start with!</p>
                                <p><ins>The Universe</ins></p>
                                <p>As I mentioned before, I love learning and talking about the lore. There’s so much to talk about though that it can be a bit overwhelming to start! The general summary I always give to new people is this:</p>
                                <p>The universe is in the 42nd millennium. Humanity has spread across the stars, forming a great empire known as the Imperium of Man. However, they are always at war, either with aliens (called xenos) or locked in a long civil war amongst themselves with the forces of Chaos. The brave men and women of the Imperium have to face down terrible odds, against the massive green hordes of the Orks, the technological supremacy and fearsome battlesuits of the Tau, or the ever consuming hunger of the Tyranids… </p>
                                <img src="nids.jpg" alt=""></img>
                                <p>Brave soldiers of the Imperial Guard, facing down a Tyranid invasion. Artist credit: lathander1987 on Deviantart.</p>
                                <p>And yet, the Imperium of Man holds against these threats. The Imperial Guard, the main military fighting force of the Imperium, holds the line against these foes with a seemingly endless supply of manpower, and the thunder of their mighty guns and tanks.</p>
                                <p>However, the one thing that everyone knows from Warhammer 40k are the mighty space marines. Tall, strong, and heavily armored, the space marines fight wherever they are needed. A squad of space marines can easily turn the tide of battle for the Imperium.</p>
                                <p>Besides the space marines, the other main fighting force of the Imperium are the Sisters of Battle. They are religious fanatics, fighting to the death for the God Emperor of Mankind. They can best be described as battle nuns. Prayers and hymns protect them in battle, while they march forward and burn the heretics and xenos. </p>
                                <img src="orksm.jpg" alt=""></img>
                                <p><em>Ultramarines fighting in close quarters combat against the Orks. Artist credit: ukitakumuki on Deviantart.</em></p>
                                <p>There’s a ton of other things I haven’t touched on, but there are plenty of ways to learn about the universe if you’re interested. Personally, one of my favorite things to do is to use the Warhammer 40k wikipedia to go delving into a topic. I’ll pick something that interests me, and start reading the article. If I find something else I want to read or learn about, I’ll open up a new tab with it to read later. There are also a ton of videos on YouTube as well! My personal favorite is 40k Theories’ 40k Lore for Newcomers. He goes over a lot of lore topics in Warhammer 40k and explains them for you. He also has a pretty good timeline video of the entire 40k universe. Bricky has a few videos explaining each faction in 40k; he explains them in a comedic fashion, but they’re good explanations. Adeptus Ridiculous also has a ton of lore videos. Find something that suits you, and listen to them while in the car or working on something else!</p>
                                <a href="https://youtu.be/UszZz_XC1YE" target="_blank" rel="noreferrer" alt=""><em>Link to that entire 40k timeline I mentioned… there’s going to be a lot of confusion if you first go into it!</em></a> 
                                <p><ins>The Game</ins></p>
                                <p>Now… onto the game itself. Let me preface this by saying that the hobby is expensive, especially for some factions. There are easy ways of getting past this however, and other ways to enjoy Warhammer in terms of video games. Let me start by talking about the tabletop wargame, however. </p>
                                <p>When you first look at starting an army, you’re going to notice the awesome paint jobs that people have done online or on the box. They do not come like this; they don’t even come built. You will have to build your figures yourself, and paint them yourself (or get a friend to do it). Before you turn away or think to yourself that there’s no way you can paint them, that’s what the internet is for! There are plenty of guides to help you, and don’t give up if your first models don’t turn out well! The main thing with building and painting is learning. Keep practicing and keep learning, and you’ll find yourself improving with each model you paint!</p>
                                <img src="plastic.jpg" alt=""></img>
                                <p><em>Some unpainted Primaris Marines, standing with some Warhammer Fantasy models.</em></p>
                                <p>As for the game itself, there’s plenty of armies, and for some armies in particular, there can be a ton of models to look through. The next question you should ask yourself about starting an army is: what is my budget? What am I looking for in an army? I plan on doing more in depth looks into each of the factions, but if you know nothing about the universe and don’t want to spend much on the game, there’s a way to enjoy the game without busting the bank. </p>
                                <p>And that would be Kill Team, or Kill Team Classic rather. Warhammer 40k focuses on large armies duking it out on the battlefield, and with how many squads you need or heavy firepower, the costs can tally up quickly. With Kill Team, it focuses on an elite squad combat system. Each faction is narrowed down to a select few models, and there’s your entire list. For some factions, you can easily get away with purchasing a single box of models. Kill Team Classic still plays in a very similar fashion to standard 40k as well, meaning that you can learn the intricacies of the game without getting too invested into it. </p>
                                <p>And for those of you wondering why I say “Kill Team Classic,” well there’s a reason for that. The recent edition to Kill Team changed the game entirely, making it a completely new game rather than a small scale 40k. You can still use the models from the new edition though, and there are some beautiful models that come with the starter kit. But I would recommend finding a PDF of Kill Team Classic online and starting there.</p>
                                <img src="orkvsnazi.jpg" alt="orkvsnazi"></img>
                                <p>After getting your feet wet with Kill Team, or maybe you have some friends who are willing to tone down their own armies with you, you can choose what army you want to get into. If you’re more of a money-oriented kind of person, I would steer away from Horde style factions, such as the Imperial Guard, Orks, and Tyranids. The best armies to start off with here would be Harlequins and Custodes. They require very few models in their armies, and they’re pretty solid overall. However if these do not suit your fancy, I would recommend looking on EBay for models. Most of the time they will come painted, so you might have a batch of mixed models making up your entire army. If you’re worried about gameplay, the Space Marines are the most well rounded faction despite their overwhelming model roster. Get some basic squads of space marines, with some devastators and assault squads for a well rounded infantry list. If you want a vehicle, you can’t go wrong with a Rhino or a Predator. From there, you can expand out your list depending on how you enjoy playing; you can get Primaris Intercessors for a stronger frontline, Bladeguard Veterans for a melee focused infantry unit, or Primaris Aggressors for some heavy infantry fire support. There’s tons of ways to expand out your army from there!</p>
                                <p>If you know what kind of playstyle you enjoy, I have some recommendations as well. If you prefer ranged combat, the Astra Militarum (aka Imperial Guard) or Tau are the best choices for you. The Guard focuses on quantity over quality with some great artillery and tanks, while the Tau feature some heavy hitting firepower and mechs. If you like melee, Orks, Tyranids, and Drukhari and the way to go. The first two are more horde style, so if you want to save on money, the Dark Eldar (basically just Dark Elves) are the best choice for you. The Tyranids can be more focused and specialized than the Orks, but nobody can hate the Orks because of their fun mechanics and lore! Want a fast and maneuverable team? Craftworld Eldar or Harlequins. Want a tanky team? Necrons or Death Guard. Want a spellcasting team? Craftworld Eldar or Thousand Sons. There are plenty of playstyles to choose from!</p>
                                <p>With that, I think I’m finally done explaining Warhammer 40k to you. I didn’t cover the rules and gameplay, nor the factions themselves. The best way to learn the game is to play with friends and meet some new people! With that concluded, I wish you all luck in your games. May the dice gods favor you!</p>
                                <img src="ssm.jpg" alt=""></img>
                                <p><em>For the Emperor! Artist credit: pierreloyvet on Artlords.</em></p>
                                <p></p>
                                <p></p>
                            </div>
                        </div>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}