import React from 'react'
import "./RPGBlog.css"
import { Container, Row, Col } from "react-bootstrap"
import RPGnav from "../RPGnav"

export default function Campaign() {
    return (
        <div>
            <RPGnav />
            
            <Container>
                <Row>
                    <Col>
                        <div className="campaign">
                            <div className="chapterone">
                                <h1>We Put the Pain in Campaign</h1>
                                <h2>The narrative for our D&D 2E Campaign Chapter 1</h2>
                                <div className="byline">Mr. L November 10th, 2021</div>
                                <img src="dndmap.png" alt=""></img>
                                <p>The band of lost adventurers:</p>
                                <p>It was a worrisome day in the woodland village of Hochoch.  The mayor had sent a band of farmers out with the yearly crop tribute over a week ago and they were late in returning.  Not only were the farmhands needed to tend to the remaining crops, but the carts that they travelled with would be needed to help bring in the remainder of the crops for the winter.  Mayor Willheim put out a notice for anyone to come to his aide and go looking for the lost wagon caravan and find out what happened to his people and the tribute crop that was due in Hookhill.  The ones that answered his request for help were not what he was expecting.  </p>
                                <p>There was a dwarven priest of Pholtus, Morgrym Sunspeaker, an elven diplomat’s nephew with a long rambling title, Mireth Elajor and a half-elven minstrel named Henri Descateaux.</p>
                                <p>Now, demi-humans were not common in Hochoch, elves moreso than dwarves which were rare, but Willheim was desperate.  The crops in the fields needed to be reaped and brought in for storage or they would spoil and the farmhands would be needed along with the carts.  He offered the group a small sum of money to track the caravan and bring back whatever they could find.  The three adventurers set out almost immediately after gathering up some pastries and moonshine from local merchants and set out into the Dim Forest woods along the trade route to Hookhill.</p>
                                <p>The group travelled southeast for two days before noticing that there were wagon tracks which led off into the woods on the southern side of the road.  Deciding to check out the tracks, they headed deeper into the woods until they came across the Javan River.  Finding a crossing point, just as darkness was coming, they decided to set up camp.  As the group was about to head off to sleep, some noise was heard up a nearby hill.  Mireth and Henri set off scouting up the hill to see what was transpiring.  They were able to see a goblin campsite, where a wagon and a fairly smashed wagon were present, along with a cave leading into the hillside.  There were a few goblins dancing around a campfire, cooking what looked like a horse or mule on the fire.  The group gathered back together and decided on a plan.</p>
                                <p>Since Morgrym was not very stealthy, Mireth would cast an enlarge spell on him so that when he came crashing through the woods, he would be a giant-sized dwarf.  Meanwhile, Mireth and Henri would sweep around to opposite sides to try and encircle the goblins.  Once the group was set, Morgrym came crashing up the hill and into the clearing, startling the goblins, putting them on the defensive, it's not often that a giant dwarf comes crashing through the woods with a mace and shield screaming at you.  Henri shot one with his short bow, striking it in the ribs, killing it instantly.  Mireth threw a dart at another, striking it but not for much damage, causing it to retreat into the cave.  The remaining two goblins moved towards Morgrym, trying to flank him.</p>
                                <p>Henri shot one of the two goblins fighting Morgrym in the back, killing another, while Morgrym battled with the remaining goblin.  Mireth noticed that something was crawling out of the cave, trying to hide among some debris.  As Morgrym dispatched the last remaining goblin with his mace, a roar could be heard from the cave as an ogre and 2 more goblins emerged, looking around angrily and finding Morgrym on the opposite side of the fire standing over two of their dead comrades.</p>
                                <p>Mireth snuck up behind the broken cart, trying to get closer to whatever moved out of the cave while Henri moved back to a flanking position to get in additional bow shots.  Morgrym stood in the firelight and challenged the ogre, but made sure to keep the fire between them as he was a little wounded and did not want to face an additional three enemies by himself.  He prayed for Pholtus' light to heal him a little, but kept himself well out of range of the enemies.</p>
                                <p>That is when the crawling figure reached out and grabbed one of the goblins, pulling him down into a wrestling match.  Henri fired at the Ogre, hitting it and just making it more mad as it charged towards Morgrym right through the fire, kicking the wood and flames all around the area, catching the carts on fire.  Morgrym moved around to the front of the good cart and tried to dump the firey grain over onto the Ogre, but he couldn't lift the entire cart.  The Ogre then started smashing his way through the cart.  Henri killed the other goblin, which was trying to flank around Morgrym with another arrow shot to the body.  Meanwhile, Mireth found that a human captive, badly injured, was fighting with the last remaing goblin.  Mireth helped him dispatch the goblin, then started working on freeing him from his bonds.</p>
                                <p>Once the human prisoner was freed, Mireth gave him his dagger and the human ran toward the ogre from behind, striking it in the back.  The ogre roared in rage and backhanded him, sending him into a heap on the ground, blood pouring from his mouth as his head struck the ground.  Henri fired another shot into the Ogre's chest while Morgrym moved to engage the creature.  Morgrym could not find a good purchase with his mace and took a nasty punch which knocked him back several feet, wounding him further.  Henri continued to pepper the Ogre with arrows while Mireth ran up and pulled the human from combat, starting to tend to his wounds.  He was not a medic mind you, but he started wrapping him in bandages where he could see blood coming out.</p>
                                <p>With both carts now fully enflamed, the campsite was a mess.  Morgrym was trying to keep the ogre at bay, fighting defensively while Henri continued to strike the creature with arrows, finally felling the creature with a shot right to its heart, dropping it almost on top of Morgrym, who slumped over in pain and injury, calling on Pholtus to once again heal himself.  With the adversaries defeated, the group took inventory of what was around.  Neither wagon was salvageable, the pack animals had all been eaten and the farmhands were all dead (a noticeable pile of human bones in the cave was a dead giveaway).  The human that was saved was healed by Morgrym back into consciousness.  He said that his name was Logan and he was a hired guide leading the group back from Hookhill when they were ambushed.  The group was able to deliver the crops to Hookhill, so the yearly tribute had been paid.  Logan was able to recover his gear from the cave along with some coins and clothing and items from the dead farmhands.  The metal parts from the wagons were recovered so that the group could prove what had happened.</p>
                                <p>The group returned to Hochoch with Logan in tow and informed the mayor of what happened.  Willheim was distraught over the complete loss of life and the wagons which were vital to the economy of the village.  The group presented him with what they had and even gave him most of the coins that were captured in the cave.  Mayor Willheim said that it would be best for us to leave the village and not inform the others of the loss.  He said that his friend the Mayor or Orlane needed some help and wrote the group a letter introducing the party to him.  He said to only give it to the mayor.  Mireth took the letter and the group headed off back into the Dim Forrest towards the farming village or Orlane.  Logan decided to join the group as he was headed back in the same direction.</p>
                                <p></p>
                                <p></p>
                                <p></p>
                            </div>
                        </div>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}
