import React from 'react'
import './RPGBlog.css'
import { Container, Col, Row } from 'react-bootstrap'

export default function PokeRPG() {
    return (
        <div>
            <Container>
                <Row>
                    <Col>
                        <div className="rpgblog">
                            <div className="pokerpg">
                                <h1>Welcome to the World of Pokemon!</h1>
                                <h2><em>A trip inside of a lesser known RPG: Pokemon Tabletop Adventures.</em></h2>
                                <div className="byline">By Tyler Leavitt October 27th, 2021</div>
                                <p>Hello everyone! I’m here today to talk about one of my recent favorite tabletop RPGs, the Pokemon Tabletop Adventures. I personally grew up playing plenty of Pokemon, and even today I still play a lot of it. One day, my dad found the rules to this RPG, and after looking through it I was hooked. My friends all agreed to play it, and now it’s one of our favorite RPGs. What is it that makes the RPG so special compared to others? For my friends, they find it an easy way to relax with a fun and silly RPG.</p>
                                <p>The Pokemon RPG is a fan creation, made by fans for fans. It’s essentially “What if we took D&D, and placed it in the Pokemon World?” As such, it’s not super well balanced and instead it’s focused on the lines of having fun. You and your Pokemon have 6 stats, which might seem familiar to fans of the series: Health, Attack, Defense, Special Attack, Special Defense, and Speed. Health is pretty self explanatory; for every 1 point in health you have, you get 3 in return. Attack and defense are your offensive and defensive stats for physical attacks, things like Tackle or Scratch. Special attack and defense are the same, but for special attacks, such as Psychic. Lastly, speed acts as your initiative in combat and grants some evasion buffs.</p>
                                <p>For those paying attention to what I’ve been writing, yes I did say you, as in your player character. You can participate in the fun too! As a Pokemon trainer, you can go into several basic classes: Ace Trainer, Breeder, Capture Specialist, Coordinator, Martial Artist, Mystic, Psychic, Ranger, or Researcher. From there, you have 7 advanced classes for each basic one, for a total of 63 advanced classes! You can do anything and practically everything there is in the world; want to focus on your favorite type of Pokemon? Type Ace has you covered. What about a crafter class? Become a Poke Ball Designer! Want to whack that Rattata with a mace? Become a Weapons Master! The best part about the entire RPG is how viable each route is for your given class. When reading through it, I was impressed with how powerful the various Ace Trainer advanced classes were. Underdog, for example, is the “Ash Ketchum” class. It focuses on keeping your Pokemon unevolved for powerful bonuses. One effect allows you to add on one stat of the Pokemon’s fully evolved form onto it right now! What this means is that you can make your Machop hit as hard as a Machamp on steroids, or your Aron can take hits like an Agron equipped with plate armor. All of the classes have their uses, so don’t bawk at any of them!</p>
                                <p><img src ="notsure.png" alt=""></img></p>
                                <p><em>The Weapons Master, with his trusty Pokemon by his side. Looks intimidating!</em></p>
                                <p>Besides your character, you also have your Pokemon. Not much has changed from the video games outside of some changes to movesets and evolutions. The real game changers come in the forms of their movement, moves, and abilities. Let me start by talking about movement, as this should be a no brainer. Movement in Pokemon obviously makes a huge difference; now you can keep your opponent’s Pokemon at bay while hitting it with ranged attacks, or close the distance to hit with a mighty melee attack that knocks the opponent back into a wall. The moves themselves had to be changed to make them fit into the RPG. While many moves still do what you expect, others have gotten entire revamps. My favorite example of this is Double Team, where not only do you increase your evasion, but you also create copies of yourself. These copies can move when you do, and you can willingly hop between each copy to use a move from it! It’s quite powerful, and very thematic for the move. Lastly, the abilities have all gotten big changes as well, once again to fit in with the RPG format. Abilities like Lightning Rod will attract all electricity to it in a large radius, and much more.</p>
                                <p><img src="poketable.png" alt=""></img></p>
                                <p><em>Holy effects Batman! </em></p>
                                <p>With all this said however, there’s a few problems that I’ve run into when running the RPG. Firstly, there’s a ton of math involved. I highly recommend keeping a calculator handy to add on all the bonuses and subtract defenses for attacks. Secondly, the EXP gain for Pokemon is crazy low. It’s meant to make campaigns last longer, however to me it makes the campaigns much more of a grind than anything else. I was doubling the amount of EXP my players got, and only recently have I moved onto quadrupling it. This fits better with the pace of my campaign, and lets my players feel major improvements to their Pokemon from session to session. However, outside of these issues the RPG is a ton of fun and I highly recommend it for any Pokemon fan.</p>
                                <p>Now, how about some tips and tricks for running and playing the game? I’ll start with general ideas you should have going into it. The first idea you should have in mind is to know what your players want from the campaign. Do they want a lot of Pokemon battles? Contests? Exploration? Maybe they want a more realistic feel to it, perhaps being police officers going up against one of the various criminal organizations? Figure out what everyone wants from the campaign and stick with it. My friends wanted a D&D but Pokemon campaign, so that’s what I gave them. For many battles, they have to manage their own trainers and avoid attacks alongside their own Pokemon. They can buy various weapons and armors to equip themselves with to make them more of a threat on the battlefield. Another thing is to determine how everyone wants to treat AOE attacks. What I mean by this is primarily friendly fire. If someone uses Fire Blast, should it hit friendlies? What about an effect move, such as Growl? Depending on what players want, this can greatly affect how they fight!</p>
                                <p>Let me move onto some tips for the players next. The first thing is, regardless of how you responded to AOE friendly fire damage, to always keep it in mind. I cannot explain how many times my friends have gotten hit by column attacks, such as Bubblebeam, from an enemy Pokemon. Always keep in mind your positioning! While going through the campaign, also think about what classes you would like to take up. Do you want to focus on your favorite type? Or maybe you want to be a team support? Do you want to focus on Pokemon battles, or outside of combat? Find out what you want to do, and stick with it. Maybe it’s something you thought would be fun, or maybe you want to focus on your favorite Pokemon. Whatever the reason may be, keep that end goal in mind. Lastly is a tip that will be pretty self-explanatory for any players of the games, but keep in mind type coverage. My friends all try to keep a good type coverage for their own party, but they often forget about each other’s Pokemon when it comes to battles. You do have your friends to help you for most of the campaign, after all!</p>
                                <p><img src="poketrainers.png" alt=""></img></p>
                                <p><em>The Type Ace, now making a one type theme team useful.</em></p>
                                <p>And now finally, what about the GM? The first and most helpful tip is to keep all of the NPC Pokemon’s stats and attacks as easy to calculate as possible. If an attack does 1d10+8, and the Pokemon has 8 attack, then write down that the attack does 1d10+16 instead. It helps keep it quick in terms of math. Additionally, I recommend thinking outside the box and having fun with designing the campaign! You can easily make the campaign take place in one or multiple regions from the video games, or make your own. For my own campaign, I made my own region based off of Italy and the Balkans. It has a heavy Roman and Greek influence to much of it, with ancient ruins for my players to explore through. With this focus, I also made my criminal organization based off of 1930s/40s style Italian mobsters, complete with pinstripe suits. Alongside that, it gave me some themes for my gyms. Since a lot of the region is focused on archeology, history, and Roman influences, I had a rock gym focused on archeology, a steel gym for history, and a psychic and fighting gym to represent Rome’s philosophy and gladiator fights. Then, the other gyms I designed were based on Greek mythology; a fairy gym for the goddess of love, fire gym for the apocalypse and war, etc. I even went ahead and further customized these battles by adding in special rules for my playerst. For the fighting gym, it took place in a colosseum, and so the players had to fight alongside their Pokemon. The rock gym has several faux rocks around the arena that they could destroy for helpful items. All of this ramps up to the Elite 4, who are located on top of a mighty mountain and based off of the Greek/Roman gods. Another helpful tip is how you want to pace the entire campaign. I wanted to keep my campaign relatively fast, so we could get to the end of it without taking 10+ years to do it. As such, I typically run 1 session as a “wilds” session, where my players travel to the next town and get an intro to the town. They can then learn about important characters and places there. Then, I have a “town” session, where my players will do something in the town or around the area. In between sessions, I run gym battles and contests, that way we don’t spend an hour with one person fighting the gym leader while everyone else has nothing to do. Lastly, if you have the entire world open for your players to roam, I would keep a list of what Pokemon the gym leaders have, including all or most evolutions. That way, if the players come to any of the gyms, you can easily figure out what Pokemon to throw at them. In the end, the goal is to have fun with it!</p>
                                <p>With all of this said and done, I highly recommend giving the RPG a try if you’re a fan of the series. I know with how much I talked about it I might’ve overwhelmed you with information, but don’t let that discourage you! It’s just what I’ve learned from running it so far, and wanted to pass onto you all. It’s a very fun and silly game if you let it be. Just remember to have fun, and catch ‘em all!</p>
                                
                            </div>
                        </div>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}